#!/bin/bash
set -e

# variables
RUN_TESTS=bin/Debug/netcoreapp2.2/tests.dll

# running tests
cd tests

echo "build ..."
dotnet build

echo "clear old..."
rm -rf data/*actual*.txt

echo "prepare output results ..."
for i in "default" "quiet" "normal" "verbose" "veryVerbose" "debug"
do
    echo " - prepare: $i ..."
    dotnet $RUN_TESTS prepare output $i > data/output-actual-$i.txt 2> data/error-actual-$i.txt
done

echo "prepare progress results ..."
for i in "default" "quiet"
do
    echo " - prepare: $i ..."
    dotnet $RUN_TESTS prepare progress $i > data/progress-actual-$i.txt
done

echo "run tests ..."
dotnet $RUN_TESTS
