name: Check

on:
    push:
        branches:
            - master
            - main
    pull_request:
    schedule:
        -   cron: '0 3 * * *'

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
                dotnet: [9.0.200]
        runs-on: ${{ matrix.os }}
        name: "Build on ${{ matrix.os }}"

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: ${{ matrix.dotnet }}

            -   name: Run build
                run: ./build.sh

    tests:
        runs-on: macos-latest
        name: "Check application"

        steps:
            -   uses: actions/checkout@v4

            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 9.x

            -   name: Run tests
                env:
                    DOTNET_ROLL_FORWARD: latestMajor
                run: ./build.sh -t tests
